services:
  app:
    image: readme-generator:latest 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../.git:/app/data/.git
      - ../Solutions:/app/data/Solutions
      - ./appsettings.json:/app/appsettings.json
      - ./data:/app/data/
      - ./README.md:/app/data/README.md
    entrypoint: ["dotnet", "Quera.dll"] 
    # command: ["-w", "Data/"]
