services:
  app:
    image: readme-generator:latest 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../.git:/app/data/.git
      - ../Solutions:/app/data/Solutions
      - ../README.md:/app/data/README.md:rw
      - ./appsettings.json:/app/appsettings.json
      - ./data/cache.db:/app/data/cache.db
      - ./data/ReadmeTemplate.md:/app/data/ReadmeTemplate.md
    entrypoint: ["dotnet", "Quera.dll"]
    # command: ["-w", "Data/"]
